# Generated by Django 3.2.6 on 2021-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('nickname', models.CharField(max_length=200)),
                ('point', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
