# Generated by Django 3.2.6 on 2021-08-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='choice',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(null=True, upload_to='facility'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='review'),
        ),
        migrations.AlterField(
            model_name='space',
            name='mainimage',
            field=models.ImageField(null=True, upload_to='mainimage'),
        ),
    ]
